version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "7000:80/tcp"
    environment:
      TZ: 'Asia/Tokyo'
      WEBPASSWORD: 'GetYourOwnPassword'
    volumes:
      - '$HOME/docker/dns/etc-pihole/:/etc/pihole/'
      - '$HOME/docker/dns/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped