version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "7000:80/tcp"
    environment:
      TZ: 'America/New_York'
    volumes:
      - {{ user_path }}/dns/etc-pihole/:/etc/pihole/
      - {{ user_path }}/dns/etc-dnsmasq.d/:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - proxy_default
networks:
  proxy_default:
    external: true
