version: '2.1'
services:
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - /home/bl/docker/flame/:/app/data
    ports:
      - 7001:5005
    restart: unless-stopped
