version: '2.1'
services:
  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - {{ user_path }}/flame/:/app/data
    ports:
      - 7001:5005
    restart: unless-stopped
    networks:
      - proxy_default
networks:
  proxy_default:
    external: true
