version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/New_York
      - PLEX_CLAIM=
      - ADVERTISE_IP
    hostname: <hostname>
    volumes:
      - /mnt/docker/plex/:/config
      - /mnt/docker/plex/temp:/transcode
      - /mnt/media/:/data
      networks:
      - proxy_default
networks:
  proxy_default:
    external: true
