version: "2.1"
services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - CHECK_FREQUENCY=240
    volumes:
      - /mnt/data/podgrab/config:/config
      - /mnt/data/podgrab/data:/assets
    ports:
      - 7002:8080
    restart: unless-stopped