version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '8181:81'
    environment:
      DISABLE_IPV6: 'true'
      DB_SQLITE_FILE: "/mnt/docker/proxy/database.sqlite"
    volumes:
      - /mnt/docker/proxy/data:/data
      - /mnt/docker/proxy/letsencrypt:/etc/letsencrypt
