version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '8181:81'
    environment:
      DISABLE_IPV6: 'true'
    volumes:
      - "{{ user_path }}/proxy/data:/data"
      - "{{ user_path }}/proxy/letsencrypt:/etc/letsencrypt"
