---
version: "2.1"
services:
  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - {{ user_path }}/smokeping/config:/config
      - {{ user_path }}/smokeping/data:/data
    ports:
      - 7004:80
    restart: unless-stopped
    networks:
      - proxy_default
networks:
  proxy_default:
    external: true
