---
version: "2.1"
services:
  nginx:
    image: lscr.io/linuxserver/nginx
    container_name: startpage
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/bl/docker/startpage/:/config
    ports:
      - 7008:443
    restart: unless-stopped
    networks:
      - proxy_default
networks:
  proxy_default:
    external: true
