version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - {{ user_path }}/uptime:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7006:3001
    networks:
      - proxy_default
networks:
  proxy_default:
    external: true
