---
version: "2.1"
services:
  nginx:
    image: lscr.io/linuxserver/nginx
    container_name: wiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /mnt/docker/wiki/:/config
    ports:
      - 7005:443
    restart: unless-stopped